apiVersion: v1
kind: Pod
metadata: 
    name: backend-server
    labels:
        tier: backend
        app: goserver
spec:
    securityContext:
       seccompProfile:
         type: RuntimeDefault
    containers:
        - name: goserver
          image: 245578940568.dkr.ecr.us-east-2.amazonaws.com/terrascan-e2e-test:terrascan
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true   
          resources:
            requests:
                cpu: "1"
                memory: "256Mi"
            limits:
                cpu: "1"
                memory: "256Mi"  
          readinessProbe:
            exec:
            command:
            - go 
            - version
            periodSeconds: 10
            initialDelaySeconds: 10

    # initContainers:
    #   - name: initserver     
    #     image: terrascantest.azurecr.io/ngin
