apiVersion: v1
kind: Pod
metadata: 
    name: gcp-server
    labels:
        tier: gcp-server
        app: gcp-server-goserver
spec:
    securityContext:
       seccompProfile:
         type: RuntimeDefault
    containers:
        - name: goserver
          image: gcr.io/accurics/terrascan-e2e-test:terrascan@sha256:a7185142bbef5ccad92fc9bca0e09a522c2d163efcaa472fd31987d68ff9c61d
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true 
          readinessProbe:
            exec:
            command:
            - go 
            - version
            periodSeconds: 10
            initialDelaySeconds: 10
